#!/bin/bash

# Check if the target directory exists or create it
if [ ! -d "/tmp/u" ]; then
  mkdir -p "/tmp/u"
fi

# Move files starting with uppercase letters to the "/tmp/u" directory
mv [[:upper:]]* /tmp/u

